/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Management;

import Database.Bdd;
import Database.Logs;
import Database.ResultSetTableModel;
import java.sql.ResultSet;
import javax.swing.JComponent;
import javax.swing.JTable;
import java.util.Arrays;
import javax.swing.table.TableColumn;

/**
 *
 * @author edmae
 */
public class ChangePassword extends javax.swing.JPanel {

    private final Bdd mBdd;
    private Integer ID = -1;
    private ResultSet rs;
    private String PASSWORD = "";

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        initComponents();
        mBdd = new Bdd();
        jTable1.setModel(new ResultSetTableModel(mBdd.querySelectAll("employee")));
        btn_change.setEnabled(false);
        jp_new.setEnabled(false);
        txt_validator.setEnabled(false);
    }
    
    public void updateJTable() {
        //Table
        jTable1.setModel(new ResultSetTableModel(mBdd.querySelectAll("employee")));
        TableColumn col1 = jTable1.getColumnModel().getColumn(5);
        col1.setMinWidth(0);
        col1.setMaxWidth(0);
        //Component
        jp_new.setText("");
        jp_old.setText("");
        btn_change.setEnabled(false);
        jp_new.setEnabled(false);
        txt_validator.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_change = new javax.swing.JButton();
        jp_old = new javax.swing.JPasswordField();
        jp_new = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txt_id = new javax.swing.JLabel();
        txt_error = new javax.swing.JLabel();
        txt_validator = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 153));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "Sex"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Change Password");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Old Password");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("New Password");

        btn_change.setText("Change");
        btn_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changeActionPerformed(evt);
            }
        });

        jp_old.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jp_oldActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID:");

        txt_id.setForeground(new java.awt.Color(255, 255, 255));
        txt_id.setText("...");

        txt_error.setForeground(new java.awt.Color(204, 0, 0));

        txt_validator.setForeground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jp_new)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_validator, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(29, 29, 29)
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_change)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jp_old, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txt_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_old))
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_change)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jp_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_validator, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        JComponent comp = (JComponent) evt.getComponent();
        JTable table = (JTable) comp;
        int row = table.getSelectedRow();
        this.ID = Integer.valueOf(table.getModel().getValueAt(row, 0).toString());
        this.PASSWORD = table.getModel().getValueAt(row, 5).toString();
        txt_id.setText("" + this.ID);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changeActionPerformed
        mBdd.queryUpdate("employee", new String[]{"PASSWORD"}, new String[]{String.valueOf(jp_new.getPassword())}, "ID = "+this.ID);
        jTable1.setModel(new ResultSetTableModel(mBdd.querySelectAll("employee")));
        txt_validator.setEnabled(true);
        txt_validator.setText("Password changed");
        jp_new.setText("");
        jp_old.setText("");
        btn_change.setEnabled(false);
        jp_new.setEnabled(false);
        Logs.setLogMessage("Change Password","Update employee password with ID: " + this.ID);
    }//GEN-LAST:event_btn_changeActionPerformed

    private void jp_oldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jp_oldActionPerformed
        // TODO add your handling code here:
        System.out.println(this.ID);
        if(this.ID == -1){
            txt_error.setVisible(true);
            txt_error.setText("Select an employee from the list.");
            return;
        }
            
        String clause = "ID = '" + this.ID + "' AND PASSWORD = '" + String.valueOf(jp_old.getPassword()) + "'";
        try{
            rs = mBdd.querySelectAll("employee", clause);
            
            if(rs.next()){
                txt_error.setVisible(false);
                btn_change.setEnabled(true);
                jp_new.setEnabled(true);
            }else{
                btn_change.setEnabled(false);
                jp_new.setEnabled(false);
                txt_error.setVisible(true);
                txt_error.setText("Password incorrect");
                return;
            }
                
            
        }catch(Exception e){}
    }//GEN-LAST:event_jp_oldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_change;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPasswordField jp_new;
    private javax.swing.JPasswordField jp_old;
    private javax.swing.JLabel txt_error;
    private javax.swing.JLabel txt_id;
    private javax.swing.JLabel txt_validator;
    // End of variables declaration//GEN-END:variables
}
