


import java.awt.CardLayout;
import Management.AddEmployee;
import Management.ChangePassword;
import Management.LogsList;
import Management.ManagerLog;
import Management.ModifyEmployee;
import Management.PettyCash;
import Management.RemoveEmployee;
import Management.ViewList;
import Management.TransactionList;
import javax.swing.JLabel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author edmae
 */
public class Management extends javax.swing.JPanel {
    private final CardLayout cardLayout = new CardLayout();
    private final ViewList mViewList = new ViewList();
    private final ModifyEmployee mModifyEmployee = new ModifyEmployee();
    private final RemoveEmployee mRemoveEmployee = new RemoveEmployee();
    private final ChangePassword mChangePassword = new ChangePassword();
    private final TransactionList mTransactionList = new TransactionList();
    private final PettyCash mPettyCash = new PettyCash();
    private final LogsList mLogsList = new LogsList();
    private ManagerLog mManagerLog;
    /**
     * Creates new form Management
     */
    public Management() {
        initComponents();
        
        pnl_cardLayout.setLayout(cardLayout);
        setLockOnManagement();
        mManagerLog = new ManagerLog(new JLabel[]{txt_addEmployee,
                                                    txt_changePass,
                                                    txt_modifyEmployee,
                                                    txt_removeEmployee,
                                                    txt_transaction,
                                                    txt_viewList,
                                                    txt_pettycash,
                                                    txt_logs});
        
        setCardLayout();
        
    }
    
    private void setCardLayout(){
        
        pnl_cardLayout.add(mManagerLog, "ManagerLog");
        pnl_cardLayout.add(mViewList, "ViewList");
        pnl_cardLayout.add(new AddEmployee(), "AddEmployee");
        pnl_cardLayout.add(mModifyEmployee, "ModifyEmployee");
        pnl_cardLayout.add(mRemoveEmployee, "RemoveEmployee");
        pnl_cardLayout.add(mChangePassword, "ChangePassword");
        pnl_cardLayout.add(mTransactionList, "TransactionList");
        pnl_cardLayout.add(mPettyCash, "PettyCash");
        pnl_cardLayout.add(mLogsList, "LogsList");
    }
    
    public void setLockOnManagement(){
        txt_addEmployee.setVisible(false);
        txt_changePass.setVisible(false);
        txt_modifyEmployee.setVisible(false);
        txt_removeEmployee.setVisible(false);
        txt_transaction.setVisible(false);
        txt_viewList.setVisible(false);
        txt_pettycash.setVisible(false);
        txt_logs.setVisible(false);
        
        cardLayout.show(pnl_cardLayout, "ManagerLog");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txt_addEmployee = new javax.swing.JLabel();
        txt_modifyEmployee = new javax.swing.JLabel();
        txt_removeEmployee = new javax.swing.JLabel();
        txt_viewList = new javax.swing.JLabel();
        pnl_cardLayout = new javax.swing.JPanel();
        txt_changePass = new javax.swing.JLabel();
        txt_transaction = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txt_pettycash = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txt_logs = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 153));
        setMaximumSize(new java.awt.Dimension(610, 450));
        setMinimumSize(new java.awt.Dimension(610, 450));
        setPreferredSize(new java.awt.Dimension(610, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_title.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        txt_title.setForeground(new java.awt.Color(255, 255, 255));
        txt_title.setText("Management");
        add(txt_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 165, 39));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 56, 590, 10));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 84, 12, 301));

        txt_addEmployee.setFont(new java.awt.Font("Book Antiqua", 0, 11)); // NOI18N
        txt_addEmployee.setForeground(new java.awt.Color(255, 255, 255));
        txt_addEmployee.setText("Add employee");
        txt_addEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_addEmployeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_addEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_addEmployeeMouseExited(evt);
            }
        });
        add(txt_addEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 81, 29));

        txt_modifyEmployee.setFont(new java.awt.Font("Book Antiqua", 0, 11)); // NOI18N
        txt_modifyEmployee.setForeground(new java.awt.Color(255, 255, 255));
        txt_modifyEmployee.setText("Modify employee");
        txt_modifyEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_modifyEmployeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_modifyEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_modifyEmployeeMouseExited(evt);
            }
        });
        add(txt_modifyEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 27));

        txt_removeEmployee.setFont(new java.awt.Font("Book Antiqua", 0, 11)); // NOI18N
        txt_removeEmployee.setForeground(new java.awt.Color(255, 255, 255));
        txt_removeEmployee.setText("Remove employee");
        txt_removeEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_removeEmployeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_removeEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_removeEmployeeMouseExited(evt);
            }
        });
        add(txt_removeEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 31));

        txt_viewList.setFont(new java.awt.Font("Book Antiqua", 0, 11)); // NOI18N
        txt_viewList.setForeground(new java.awt.Color(255, 255, 255));
        txt_viewList.setText("View List");
        txt_viewList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_viewListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_viewListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_viewListMouseExited(evt);
            }
        });
        add(txt_viewList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, -1));

        javax.swing.GroupLayout pnl_cardLayoutLayout = new javax.swing.GroupLayout(pnl_cardLayout);
        pnl_cardLayout.setLayout(pnl_cardLayoutLayout);
        pnl_cardLayoutLayout.setHorizontalGroup(
            pnl_cardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        pnl_cardLayoutLayout.setVerticalGroup(
            pnl_cardLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        add(pnl_cardLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 450, 300));

        txt_changePass.setFont(new java.awt.Font("Book Antiqua", 0, 11)); // NOI18N
        txt_changePass.setForeground(new java.awt.Color(255, 255, 255));
        txt_changePass.setText("Change password");
        txt_changePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_changePassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_changePassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_changePassMouseExited(evt);
            }
        });
        add(txt_changePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        txt_transaction.setFont(new java.awt.Font("Book Antiqua", 0, 11)); // NOI18N
        txt_transaction.setForeground(new java.awt.Color(255, 255, 255));
        txt_transaction.setText("Transaction list");
        txt_transaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_transactionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_transactionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_transactionMouseExited(evt);
            }
        });
        add(txt_transaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 90, 10));

        txt_pettycash.setFont(new java.awt.Font("Book Antiqua", 0, 11)); // NOI18N
        txt_pettycash.setForeground(new java.awt.Color(255, 255, 255));
        txt_pettycash.setText("Petty Cash");
        txt_pettycash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_pettycashMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_pettycashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_pettycashMouseExited(evt);
            }
        });
        add(txt_pettycash, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 90, 10));

        txt_logs.setFont(new java.awt.Font("Book Antiqua", 0, 11)); // NOI18N
        txt_logs.setForeground(new java.awt.Color(255, 255, 255));
        txt_logs.setText("Logs");
        txt_logs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_logsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_logsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_logsMouseExited(evt);
            }
        });
        add(txt_logs, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_addEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_addEmployeeMouseEntered
        // TODO add your handling code here:
        txt_addEmployee.setFont(new java.awt.Font("Book Antiqua", 1, 12));
    }//GEN-LAST:event_txt_addEmployeeMouseEntered

    private void txt_addEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_addEmployeeMouseExited
        // TODO add your handling code here:
        txt_addEmployee.setFont(new java.awt.Font("Book Antiqua", 0, 11));
    }//GEN-LAST:event_txt_addEmployeeMouseExited

    private void txt_modifyEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_modifyEmployeeMouseEntered
        // TODO add your handling code here:
        txt_modifyEmployee.setFont(new java.awt.Font("Book Antiqua", 1, 12));
    }//GEN-LAST:event_txt_modifyEmployeeMouseEntered

    private void txt_modifyEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_modifyEmployeeMouseExited
        // TODO add your handling code here:
        txt_modifyEmployee.setFont(new java.awt.Font("Book Antiqua", 0, 11));
    }//GEN-LAST:event_txt_modifyEmployeeMouseExited

    private void txt_removeEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_removeEmployeeMouseEntered
        // TODO add your handling code here:
        txt_removeEmployee.setFont(new java.awt.Font("Book Antiqua", 1, 12));
    }//GEN-LAST:event_txt_removeEmployeeMouseEntered

    private void txt_removeEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_removeEmployeeMouseExited
        // TODO add your handling code here:
        txt_removeEmployee.setFont(new java.awt.Font("Book Antiqua", 0, 11));
    }//GEN-LAST:event_txt_removeEmployeeMouseExited

    private void txt_viewListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_viewListMouseEntered
        // TODO add your handling code here:
        txt_viewList.setFont(new java.awt.Font("Book Antiqua", 1, 12));
    }//GEN-LAST:event_txt_viewListMouseEntered

    private void txt_viewListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_viewListMouseExited
        // TODO add your handling code here:
        txt_viewList.setFont(new java.awt.Font("Book Antiqua", 0, 11));
    }//GEN-LAST:event_txt_viewListMouseExited

    private void txt_addEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_addEmployeeMouseClicked
        // TODO add your handling code here:
        cardLayout.show(pnl_cardLayout, "AddEmployee");
    }//GEN-LAST:event_txt_addEmployeeMouseClicked

    private void txt_modifyEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_modifyEmployeeMouseClicked
        // TODO add your handling code here:
        mModifyEmployee.updateJTable();
        cardLayout.show(pnl_cardLayout, "ModifyEmployee");
    }//GEN-LAST:event_txt_modifyEmployeeMouseClicked

    private void txt_viewListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_viewListMouseClicked
        // TODO add your handling code here:
        mViewList.updateJTable();
        cardLayout.show(pnl_cardLayout, "ViewList");
    }//GEN-LAST:event_txt_viewListMouseClicked

    private void txt_removeEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_removeEmployeeMouseClicked
        // TODO add your handling code here:
        mRemoveEmployee.updateJTable();
        cardLayout.show(pnl_cardLayout, "RemoveEmployee");
    }//GEN-LAST:event_txt_removeEmployeeMouseClicked

    private void txt_changePassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_changePassMouseEntered
        // TODO add your handling code here:
        txt_changePass.setFont(new java.awt.Font("Book Antiqua", 1, 12));
    }//GEN-LAST:event_txt_changePassMouseEntered

    private void txt_changePassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_changePassMouseExited
        // TODO add your handling code here:
        txt_changePass.setFont(new java.awt.Font("Book Antiqua", 0, 11));
    }//GEN-LAST:event_txt_changePassMouseExited

    private void txt_changePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_changePassMouseClicked
        // TODO add your handling code here:
        mChangePassword.updateJTable();
        cardLayout.show(pnl_cardLayout, "ChangePassword");
    }//GEN-LAST:event_txt_changePassMouseClicked

    private void txt_transactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_transactionMouseClicked
        // TODO add your handling code here:
        mTransactionList.updateJTable();
        cardLayout.show(pnl_cardLayout, "TransactionList");
    }//GEN-LAST:event_txt_transactionMouseClicked

    private void txt_transactionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_transactionMouseEntered
        // TODO add your handling code here:
        txt_transaction.setFont(new java.awt.Font("Book Antiqua", 1, 12));
    }//GEN-LAST:event_txt_transactionMouseEntered

    private void txt_transactionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_transactionMouseExited
        // TODO add your handling code here:
        txt_transaction.setFont(new java.awt.Font("Book Antiqua", 0, 11));
    }//GEN-LAST:event_txt_transactionMouseExited

    private void txt_pettycashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_pettycashMouseClicked
        // TODO add your handling code here:
        mPettyCash.updateJTable();
        cardLayout.show(pnl_cardLayout, "PettyCash");
    }//GEN-LAST:event_txt_pettycashMouseClicked

    private void txt_logsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_logsMouseClicked
        // TODO add your handling code here:
        mLogsList.updateJTable();
        cardLayout.show(pnl_cardLayout, "LogsList");
    }//GEN-LAST:event_txt_logsMouseClicked

    private void txt_pettycashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_pettycashMouseEntered
        // TODO add your handling code here:
        txt_pettycash.setFont(new java.awt.Font("Book Antiqua", 1, 12));
    }//GEN-LAST:event_txt_pettycashMouseEntered

    private void txt_pettycashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_pettycashMouseExited
        // TODO add your handling code here:
        txt_pettycash.setFont(new java.awt.Font("Book Antiqua", 0, 11));
    }//GEN-LAST:event_txt_pettycashMouseExited

    private void txt_logsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_logsMouseEntered
        // TODO add your handling code here:
        txt_logs.setFont(new java.awt.Font("Book Antiqua", 1, 12));
    }//GEN-LAST:event_txt_logsMouseEntered

    private void txt_logsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_logsMouseExited
        // TODO add your handling code here:
        txt_logs.setFont(new java.awt.Font("Book Antiqua", 0, 11));
    }//GEN-LAST:event_txt_logsMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel pnl_cardLayout;
    public static javax.swing.JLabel txt_addEmployee;
    public static javax.swing.JLabel txt_changePass;
    private javax.swing.JLabel txt_logs;
    public static javax.swing.JLabel txt_modifyEmployee;
    private javax.swing.JLabel txt_pettycash;
    public static javax.swing.JLabel txt_removeEmployee;
    private javax.swing.JLabel txt_title;
    public static javax.swing.JLabel txt_transaction;
    public static javax.swing.JLabel txt_viewList;
    // End of variables declaration//GEN-END:variables
}
